### ISSUE TITLE
FC when rating song using latest debug build

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#146]
I was rating a 2sf file within a zip archive, while the song was playing.  After doing so, it lagged for a few seconds, then FC'd.  The rating is still there in the browser overview, but is not displayed when the song is playing (it shows zero out of five stars).  Issue is repeatable.

I can get logcat if you're unable to recreate the issue.

**Comment by droidmjt** [comment]
i think i have fixed this long time ago, just that never uploaded the binary since i got distracted by something else. There is another bug but after im done with it, I upload a new binary

**Comment by droidmjt** [comment]
check out the latest binary from dropbox

**Comment by Level99OCR** [comment]
Got the latest, still crashing but I haven't done a clean install/scan.  I'll get on that as soon as I'm able.  Sorry for the delay in responding to the update.

**Comment by droidmjt** [comment]
Do a full rescan. I can't think of anything else. Does it only happen with .2sf files? Have you tested with songs in Examples.zip for example? Earlier there were numerous bugs with rating but they should be gone now. If nothing else helps, send me logcat log.

**Comment by Level99OCR** [comment]
It needed a clean install, now its working flawlessly.  Closing this!

Side note: not sure if its changes you made or a new experimental kernel for my device, but the scan seemed much snappier.  I will have to see if the filecache bug is still there but either way, latest debug seems great so far!
