### ISSUE TITLE
Crashing when file missing

### ISSUE THREAD

**Issue by AdityaMH** [droidmjt/Droidsound#482]
Some music add to playlist. when i deleted that music but not on playlist.
That become crashing and app stopped when that deleted music selected, not going to next music on list.

**Comment by droidmjt** [comment]
I'll fix it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/zgz34mz0p10sloo/droidsounde167_156.apk?dl=1
try this

**Comment by AdityaMH** [comment]
For me, still crashes.
I give example, add all midi file on folder to "that" playlist.
Then deleted one midi file on folder but not on playlist. Then select/play that deleted midi on playlist.
And the result become like this.
![Screenshot_2019-05-22-23-10-24-487_com miui home](https://user-images.githubusercontent.com/33791472/58191086-09c9fc80-7ce8-11e9-9c0f-55cdbb02d5ca.png)

For nomal music player, that going to next music/song.

**Comment by AdityaMH** [comment]
And one more thing, why they can't read kanji?
![Screenshot_2019-05-22-23-30-17-610_com droidmjt droidsounde](https://user-images.githubusercontent.com/33791472/58191992-f455d200-7ce9-11e9-9daf-633b8baa044f.png)

**Comment by droidmjt** [comment]
this is what I did, I have .xm and .mod files in /sdcard/Music/, i added few of those to Favourites playlist, then i removed those files what I just added to playlist and tried to play them from the Favourites playlist, it just skipped them,  no crash.

**Comment by droidmjt** [comment]
please verify from About page that you have build 156

**Comment by droidmjt** [comment]
rename those badly named songs again in Android using kanji and it will work, I just renamed a file to random name using kanji and the app showed them normally

**Comment by AdityaMH** [comment]
![Screenshot_2019-05-23-16-28-26-403_com droidmjt droidsounde](https://user-images.githubusercontent.com/33791472/58242868-c61fd300-7d79-11e9-9b13-844b016f4e9e.png)

About kanji, these "text" from inside file, rename randomly won't effected at all.
![Screenshot_2019-05-23-16-37-16-613_com droidmjt droidsounde](https://user-images.githubusercontent.com/33791472/58242958-f5364480-7d79-11e9-94a9-8cffb7b9968f.png)

**Comment by TheShinyCookie** [comment]
![Screenshot_20190523-125249_Droidsound-E](https://user-images.githubusercontent.com/42484937/58250631-c7410800-7d59-11e9-8786-3c35ac9bd3c7.jpg)
I have a similar issue with kanji not displaying properly.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/5c2oat8mwbv0p7s/droidsounde167_157.apk?dl=1
this should fix the kanji problem

**Comment by TheShinyCookie** [comment]
Awesome! Title now scrolls, and Kanji is displayed properly. Not sure about the crashing problem though, I haven't experienced it

**Comment by AdityaMH** [comment]
Ok, i retest from folder to playlist, and do same as before, and look fixed and no crash again.
But, playing a re-moved uncompress file/music where still listed in favorite, still crash when selected .

**Comment by droidmjt** [comment]
>>But, playing a re-moved uncompress file/music where still listed in favorite, still crash when selected 

how is that different from the previous case with MIDI files? I'm confused.

**Comment by AdityaMH** [comment]
Now different case.
1. I added some music from inside .zip file (/droidsound/dsroot/) to playlist
2. Then I moved that .zip file to external card
3. I selected that music from playlist, and crashed.

If still confused, maybe this log maybe help you.
![Screenshot_2019-05-23-16-39-06-431_com miui bugreport](https://user-images.githubusercontent.com/33791472/58326704-d3ab8a80-7e57-11e9-91d8-159ca4b8bc50.png)

I'm sorry to make you confused, I really don't konw if music from folder or from uncompressed file is different case (i give you different instruction).

About kanji, i found wrong/unnatural "kanji" titles (this from build 157).
![Screenshot_2019-05-24-18-45-44-155_com droidmjt droidsounde](https://user-images.githubusercontent.com/33791472/58326953-78c66300-7e58-11e9-8ec1-3daaa1a3bc98.png)

**Comment by droidmjt** [comment]
ah, you moved the whole archive, all right, I'll check it

**Comment by droidmjt** [comment]
could you email me the langrisser iv zip file please?

**Comment by droidmjt** [comment]
nevermind, I got the Langrisser 4 zip

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/gclyqydobnezujx/droidsounde167_158.apk?dl=1
Try this, archive problem should be fixed. I don't know why the character decoding is like that.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/3ioyye7oe7fn123/droidsounde167_159.apk?dl=1
use this instead, 158 build had a streaming bug

**Comment by AdityaMH** [comment]
Problem solved, so i closed this issue.
