### ISSUE TITLE
TXTP commands "C" and "c" not working

### ISSUE THREAD

**Issue by qwertysampletext** [droidmjt/Droidsound#508]
TXTP commands "C" and "c" (see github.com/losnoco/vgmstream/blob/master/doc/TXTP.md) don't work unless used on a stream with >8 channels.

**Comment by droidmjt** [comment]
I have fixed this problem, I'll upload new binary during this weekend.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/71xq7cvinon919r/droidsounde167_177.apk?dl=1
try this

**Comment by qwertysampletext** [comment]
Thank you, now it works, but I also forgot to mention TXTP macro "crossfade" (I haven't tested the others) didn't work with ≤8 channels and still doesn't.

**Comment by droidmjt** [comment]
you need to provide steps how to test the crossfade feature

**Comment by droidmjt** [comment]
leave a msg, I'll fix some other time
